[package]
edition = "2021"
name = "wasm-generator"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
codegen = "0.1.3"
syn = {version = "1.0.99", features = ["full", "parsing"]}
