[package]
authors = ["Crypto Garage"]
name = "bitcoin-test-utils"
version = "0.1.0"

[dependencies]
bitcoin = {version = "0.28"}
bitcoincore-rpc = {version = "0.15"}
bitcoincore-rpc-json = {version = "0.15"}
