[package]
authors = ["Crypto Garage"]
description = "Creation, signing and verification of Discreet Log Contracts (DLC) transactions."
homepage = "https://github.com/p2pderivatives/rust-dlc"
license-file = "../LICENSE"
name = "dlc"
repository = "https://github.com/p2pderivatives/rust-dlc/tree/master/dlc"
version = "0.1.0"

[dependencies]
bitcoin = {version = "0.28"}
miniscript = "7.0.0"
secp256k1-sys = {version = "0.5.2"}
secp256k1-zkp = {version = "0.6.0", features = ["bitcoin_hashes", "rand-std"]}
serde = {version = "1.0", default-features = false, optional = true}
typescript-definitions = {git = "https://github.com/onelson/typescript-definitions", branch = "no-debug-attrs", optional = true}

[features]
# for benchmarks
unstable = []
use-serde = ["serde", "bitcoin/use-serde", "secp256k1-zkp/use-serde"]

[dev-dependencies]
bitcoin = {version = "0.28", features = ["use-serde"]}
bitcoin-test-utils = {path = "../bitcoin-test-utils"}
bitcoincore-rpc = {version = "0.15.0"}
bitcoincore-rpc-json = {version = "0.15.0"}
dlc-trie = {path = "../dlc-trie"}
rayon = "1.5"
secp256k1-zkp = {version = "0.6.0", features = ["bitcoin_hashes", "rand", "rand-std", "serde", "global-context"]}
serde_json = "1.0"
