[package]
authors = ["Crypto Garage"]
description = "Structs and serialization for the Discreet Log Contract (DLC) protocol."
edition = "2018"
homepage = "https://github.com/p2pderivatives/rust-dlc"
license-file = "../LICENSE"
name = "dlc-messages"
repository = "https://github.com/p2pderivatives/rust-dlc/tree/master/dlc-messages"
version = "0.1.0"

[features]
use-serde = ["serde", "bitcoin/use-serde", "secp256k1-zkp/use-serde"]

[dependencies]
bitcoin = {version = "0.28"}
dlc = {version = "0.1.0", path = "../dlc"}
lightning = {version = "0.0.107"}
secp256k1-zkp = {version = "0.6.0", features = ["bitcoin_hashes", "rand", "rand-std"], git = "https://github.com/p2pderivatives/rust-secp256k1-zkp", branch = "musig2"}
serde = {version = "1.0", features = ["derive"], optional = true}

[dev-dependencies]
bitcoin = {version = "0.28", features = ["use-serde"]}
bitcoin-test-utils = {path = "../bitcoin-test-utils"}
dlc-messages = {path = "./", features = ["use-serde"]}
secp256k1-zkp = {version = "0.6.0", features = ["use-serde", "global-context"], git = "https://github.com/p2pderivatives/rust-secp256k1-zkp", branch = "musig2"}
serde = {version = "1.0", features = ["derive"]}
serde_json = "1.0"
